# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensehealth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='category',
            new_name='category_id',
        ),
    ]
